import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "My Manual T3 App",
  description: "Generated by learning step-by-step!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Font Awesome Kit Script */}
        <Script
          src="https://kit.fontawesome.com/52cad0a2c1.js"
          strategy="beforeInteractive"
          crossOrigin="anonymous"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
