import type { Metadata } from "next";
import "./globals.css"; // We'll create this soon for Tailwind

export const metadata: Metadata = {
  title: "My Manual T3 App",
  description: "Generated by learning step-by-step!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}